// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const getAnswer = `-- name: GetAnswer :one
SELECT
    "id", "message_id", "answer", "reaction_count"
FROM answers
WHERE
    id = $1
`

func (q *Queries) GetAnswer(ctx context.Context, id uuid.UUID) (Answer, error) {
	row := q.db.QueryRow(ctx, getAnswer, id)
	var i Answer
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.Answer,
		&i.ReactionCount,
	)
	return i, err
}

const getAnswers = `-- name: GetAnswers :many
SELECT
    "id", "message_id", "answer", "reaction_count"
FROM answers
WHERE
    message_id = $1 ORDER BY reaction_count DESC
`

func (q *Queries) GetAnswers(ctx context.Context, messageID uuid.UUID) ([]Answer, error) {
	rows, err := q.db.Query(ctx, getAnswers, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Answer
	for rows.Next() {
		var i Answer
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.Answer,
			&i.ReactionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessage = `-- name: GetMessage :one
SELECT
    "id", "room_id", "message", "reaction_count", "answered"
FROM messages
WHERE
    id = $1
`

func (q *Queries) GetMessage(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Message,
		&i.ReactionCount,
		&i.Answered,
	)
	return i, err
}

const getRoom = `-- name: GetRoom :one
SELECT
    "id", "theme"
FROM rooms
WHERE id = $1
`

func (q *Queries) GetRoom(ctx context.Context, id uuid.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, getRoom, id)
	var i Room
	err := row.Scan(&i.ID, &i.Theme)
	return i, err
}

const getRoomMessages = `-- name: GetRoomMessages :many
SELECT
    "id", "room_id", "message", "reaction_count", "answered"
FROM messages
WHERE
    room_id = $1
ORDER BY reaction_count DESC
`

func (q *Queries) GetRoomMessages(ctx context.Context, roomID uuid.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, getRoomMessages, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.Message,
			&i.ReactionCount,
			&i.Answered,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRooms = `-- name: GetRooms :many
SELECT
    "id", "theme"
FROM rooms
`

func (q *Queries) GetRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.Query(ctx, getRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(&i.ID, &i.Theme); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAnswer = `-- name: InsertAnswer :one
INSERT INTO answers
    ( "message_id", "answer" ) VALUES
    ( $1, $2 )
RETURNING "id"
`

type InsertAnswerParams struct {
	MessageID uuid.UUID
	Answer    string
}

func (q *Queries) InsertAnswer(ctx context.Context, arg InsertAnswerParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertAnswer, arg.MessageID, arg.Answer)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages
    ( "room_id", "message" ) VALUES
    ( $1, $2 )
RETURNING "id"
`

type InsertMessageParams struct {
	RoomID  uuid.UUID
	Message string
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertMessage, arg.RoomID, arg.Message)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertRoom = `-- name: InsertRoom :one
INSERT INTO rooms
    ( "theme" ) VALUES
    ( $1 )
RETURNING "id"
`

func (q *Queries) InsertRoom(ctx context.Context, theme string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertRoom, theme)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const markMessageAsAnswered = `-- name: MarkMessageAsAnswered :exec
UPDATE messages
SET
    answered = true
WHERE
    id = $1
`

func (q *Queries) MarkMessageAsAnswered(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markMessageAsAnswered, id)
	return err
}

const reactToAnswer = `-- name: ReactToAnswer :one
UPDATE answers
SET
    reaction_count = reaction_count + 1
WHERE 
    id = $1
AND 
    message_id = $2
RETURNING reaction_count
`

type ReactToAnswerParams struct {
	ID        uuid.UUID
	MessageID uuid.UUID
}

func (q *Queries) ReactToAnswer(ctx context.Context, arg ReactToAnswerParams) (int64, error) {
	row := q.db.QueryRow(ctx, reactToAnswer, arg.ID, arg.MessageID)
	var reaction_count int64
	err := row.Scan(&reaction_count)
	return reaction_count, err
}

const reactToMessage = `-- name: ReactToMessage :one
UPDATE messages
SET
    reaction_count = reaction_count + 1
WHERE
    id = $1
RETURNING reaction_count
`

func (q *Queries) ReactToMessage(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, reactToMessage, id)
	var reaction_count int64
	err := row.Scan(&reaction_count)
	return reaction_count, err
}

const removeReactionFromAnswer = `-- name: RemoveReactionFromAnswer :one
UPDATE answers
SET
    reaction_count = reaction_count - 1
WHERE
    id = $1
AND 
    message_id = $2
RETURNING reaction_count
`

type RemoveReactionFromAnswerParams struct {
	ID        uuid.UUID
	MessageID uuid.UUID
}

func (q *Queries) RemoveReactionFromAnswer(ctx context.Context, arg RemoveReactionFromAnswerParams) (int64, error) {
	row := q.db.QueryRow(ctx, removeReactionFromAnswer, arg.ID, arg.MessageID)
	var reaction_count int64
	err := row.Scan(&reaction_count)
	return reaction_count, err
}

const removeReactionFromMessage = `-- name: RemoveReactionFromMessage :one
UPDATE messages
SET
    reaction_count = reaction_count - 1
WHERE
    id = $1
RETURNING reaction_count
`

func (q *Queries) RemoveReactionFromMessage(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, removeReactionFromMessage, id)
	var reaction_count int64
	err := row.Scan(&reaction_count)
	return reaction_count, err
}
